# Generated by Django 4.2.5 on 2024-01-21 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цвет напитка')),
            ],
            options={
                'verbose_name': 'цвет винограда',
                'verbose_name_plural': 'Цвета винограда',
            },
        ),
        migrations.CreateModel(
            name='Sweetness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сладость')),
            ],
            options={
                'verbose_name': 'количество сахара',
                'verbose_name_plural': 'Количество сахара',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сорт')),
            ],
            options={
                'verbose_name': 'сорт винограда',
                'verbose_name_plural': 'Сорта винограда',
            },
        ),
        migrations.CreateModel(
            name='Vine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование вина')),
                ('factory', models.CharField(max_length=50, verbose_name='Завод изготовителя')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Введите год в формате YYYY (например, 2022)', validators=[django.core.validators.MinValueValidator(1000, message='Введите год от 1000'), django.core.validators.MaxValueValidator(3000, message='Введите год одо 3000')], verbose_name='Год розлива')),
                ('image', models.ImageField(blank=True, upload_to='vine_images', verbose_name='Этикетка')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='Описание')),
                ('tasty', models.BooleanField(default=False, help_text='Не забудь поставить галочку, если напиток тебе понравился.', verbose_name='Вкусно!')),
                ('tasting', models.BooleanField(default=False, help_text='Если вино уже продегустировано, ставь галочку.', verbose_name='Продегустировано')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дегустатор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vine_cat', to='vine.category', verbose_name='Категория')),
                ('colors', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='vine_col', to='vine.color', verbose_name='Цвет')),
                ('sweetness', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='vine_sweet', to='vine.sweetness', verbose_name='Сладость')),
                ('variety', models.ManyToManyField(blank=True, related_name='vine_var', to='vine.variety', verbose_name='Сорт винограда')),
            ],
            options={
                'verbose_name': 'винный напиток',
                'verbose_name_plural': 'Винные напитки',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vine.vine')),
            ],
        ),
    ]
