# Generated by Django 4.2.5 on 2024-01-23 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['name'], 'verbose_name': 'сорт винограда', 'verbose_name_plural': 'Сорта винограда'},
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='vine',
            name='year',
            field=models.PositiveIntegerField(help_text='Введите год в формате YYYY (например, 2022)', null=True, validators=[django.core.validators.MinValueValidator(1000, message='Введите год от 1000'), django.core.validators.MaxValueValidator(3000, message='Введите год одо 3000')], verbose_name='Год урожая'),
        ),
    ]
