# Generated by Django 4.2.5 on 2024-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine', '0002_alter_variety_options_alter_variety_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vine',
            name='author',
        ),
        migrations.AlterField(
            model_name='vine',
            name='factory',
            field=models.CharField(blank=True, max_length=50, verbose_name='Завод изготовителя'),
        ),
        migrations.AlterField(
            model_name='vine',
            name='tasting',
            field=models.BooleanField(default=True, help_text='Если вино уже продегустировано, ставь галочку.', verbose_name='Продегустировано'),
        ),
    ]
